### ISSUE TITLE
Not compatible with Laravel 10

### ISSUE THREAD

**Issue by sardorjs** [javvlon/laravel-google-chat-logger#1]
# Description
- this package turns out to be for laravel 8 
- and in version 10 monolog/AbstractProcessingHandler has changed its implementation of write(). 
- that's why it gives an error. 

- you should add in the description that it is compatible with version 8.
- or add versions for Laravel 10

### Screenshot is provided
![unnamed](https://github.com/user-attachments/assets/e1e0a384-aff1-4f58-91b6-0d04ec365a81)

**Comment by javvlon** [comment]
Could you check again, please

**Comment by sardorjs** [comment]
NC - great job, thank you
